from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from agents.troubleshoot_agent import IssueRecord


_RUNBOOK_TEMPLATE = """\
# Runbook: {title}

> **Generated:** {timestamp}
> **Cluster Context:** {cluster_context}
> **LLM Provider:** {llm_provider}
> **Status:** {status}

---

## Overview

{description}

---

## Symptoms

{symptoms}

---

## Root Cause

{root_cause}

---

## Affected Resources

{affected_resources}

---

## Fix Applied

{fix_applied}

---

## Step-by-Step Resolution

{fix_steps}

---

## Verification

{verification}

---

## Prevention & Best Practices

{prevention}

---

## Full Diagnostic Conversation

<details>
<summary>Click to expand AI analysis</summary>

{conversation}

</details>

---

*Runbook auto-generated by AI-Powered Kubernetes Troubleshooting Assistant*
"""


def _slug(text: str) -> str:
    text = re.sub(r"[^\w\s-]", "", text.lower())
    text = re.sub(r"[\s_-]+", "-", text).strip("-")
    return text[:60]


def _bullets(items: list[str]) -> str:
    if not items:
        return "_None identified_"
    return "\n".join(f"- {item}" for item in items)


def _or_placeholder(text: str, placeholder: str = "_Not yet determined_") -> str:
    return text.strip() if text and text.strip() else placeholder


class RunbookGenerator:
    def __init__(
        self,
        output_dir: Path,
        cluster_context: str = "unknown",
        llm_provider: str = "unknown",
    ) -> None:
        self._output_dir = output_dir
        self._cluster_context = cluster_context
        self._llm_provider = llm_provider
        output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, issue: IssueRecord) -> Path:
        """Write a Markdown runbook and return the file path."""
        now = datetime.now(tz=timezone.utc)
        timestamp = now.strftime("%Y-%m-%d %H:%M UTC")
        date_prefix = now.strftime("%Y%m%d-%H%M%S")

        title = self._derive_title(issue)
        slug = _slug(title)
        filename = f"{date_prefix}-{slug}.md"
        output_path = self._output_dir / filename

        # Build fix steps from the fix_applied text
        fix_steps = self._derive_fix_steps(issue)

        content = _RUNBOOK_TEMPLATE.format(
            title=title,
            timestamp=timestamp,
            cluster_context=self._cluster_context,
            llm_provider=self._llm_provider,
            status="Resolved ✅" if issue.resolved else "Under Investigation 🔍",
            description=_or_placeholder(issue.description),
            symptoms=_bullets(issue.symptoms) if issue.symptoms else _or_placeholder(""),
            root_cause=_or_placeholder(issue.root_cause),
            affected_resources=_bullets(issue.affected_resources) if issue.affected_resources
            else _or_placeholder(""),
            fix_applied=_or_placeholder(issue.fix_applied),
            fix_steps=fix_steps,
            verification=_bullets(issue.verification_steps) if issue.verification_steps
            else _or_placeholder(""),
            prevention=_or_placeholder(issue.prevention),
            conversation=issue.conversation_summary or "_No summary available_",
        )

        output_path.write_text(content, encoding="utf-8")
        return output_path

    def _derive_title(self, issue: IssueRecord) -> str:
        # Use first non-empty line of root cause if available
        if issue.root_cause:
            first_line = issue.root_cause.splitlines()[0].strip()
            if first_line:
                return first_line[:80]
        # Fall back to description
        first_line = issue.description.splitlines()[0].strip()
        return first_line[:80] if first_line else "Kubernetes Issue"

    def _derive_fix_steps(self, issue: IssueRecord) -> str:
        if not issue.fix_applied:
            return "_No fix was applied during this session._"

        lines = []
        step = 1
        for line in issue.fix_applied.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            lines.append(f"{step}. {stripped}")
            step += 1

        if issue.fix_commands:
            lines.append("")
            lines.append("**Commands executed:**")
            lines.append("```bash")
            for cmd in issue.fix_commands:
                lines.append(cmd)
            lines.append("```")

        return "\n".join(lines) if lines else "_No structured steps recorded._"

    def generate_index(self) -> Path:
        """Generate or update an index.md listing all runbooks."""
        runbooks = sorted(self._output_dir.glob("*.md"))
        runbooks = [r for r in runbooks if r.name != "index.md"]

        lines = [
            "# Kubernetes Troubleshooting Runbook Index",
            "",
            f"_Last updated: {datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
            "",
            f"Total runbooks: **{len(runbooks)}**",
            "",
            "| # | Runbook | Date |",
            "|---|---------|------|",
        ]

        for i, path in enumerate(reversed(runbooks), 1):
            # Parse date from filename prefix YYYYMMDD-HHMMSS
            date_str = path.stem[:15].replace("-", " ", 1)
            try:
                dt = datetime.strptime(path.stem[:15], "%Y%m%d-%H%M%S")
                date_str = dt.strftime("%Y-%m-%d %H:%M")
            except ValueError:
                date_str = "?"
            title = path.stem[16:].replace("-", " ").title()
            lines.append(f"| {i} | [{title}]({path.name}) | {date_str} |")

        index_path = self._output_dir / "index.md"
        index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return index_path
